#Default port is 8761
server:
  port: 80

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    enableSelfPreservation: false
    eviction-interval-timer-in-ms: 30000
    waitTimeInMsWhenSyncEmpty: 0
  serviceUrl:
    defaultZone: http://localhost:80

#Setting logging levels
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.scc: DEBUG
